name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # context: ./ # TODO seems like contecst is not needed anymore
          push: false  # TODO - push to Registry on merge with trunk
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/k8s-gitlab-ci-cd:${{ github.run_id }}
