name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dockerbuild:
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./app
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/k8s-gitlab-ci-cd:${{ GITHUB_RUN_ID }}

      - name: Push to DockerHub
        if: ${{ github.ref == 'refs/heads/master' }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./app
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/k8s-gitlab-ci-cd:${{ GITHUB_RUN_ID }}
