name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# https://github.com/marketplace/actions/deploy-to-heroku
jobs:
  heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "karma-git-fastapi" #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: "https://karma-git-fastapi.herokuapp.com/health"
          checkstring: "ok"
          delay: 5
          rollbackonhealthcheckfailed: true
