name: Pylint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - 'feat/*'
      - 'hotfix/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        cd app && pip install --no-cache-dir -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
