name: CI fastapi

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    # TODO: cache dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install --no-cache-dir -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`

  smoketest:
    needs: pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install --no-cache-dir -r requirements.txt
          sudo apt-get install -y curl jq
      - name: Smoke Test
        # Port 80 busy or closed by ufw
        run: |
          cd app
          uvicorn main:app --host 0.0.0.0 --port 8080 &
          sleep 3
          curl http://0.0.0.0:8080/isalive > getresult
          jq '.status' getresult | grep 'OK'

  dockerbuild:
    needs: smoketest
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          # context: ./ # TODO seems like context is not needed anymore
          push: false  # TODO - push to Registry on merge with trunk
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/k8s-gitlab-ci-cd:${{ github.run_id }}

  herokudeploy:
    needs: smoketest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "karma-git-fastapi"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: "https://karma-git-fastapi.herokuapp.com/isalive"
          checkstring: "OK"
          delay: 5
