name: pylint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

# LINT Jobs

  pylint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    # TODO: cache dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        cd app && pip install --no-cache-dir -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        cd app
        pylint `ls -R|grep .py$|xargs`

# Test

  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          cd app && pip install --no-cache-dir -r requirements.txt
          sudo apt-get install -y curl jq
      - name: Smoke test
        run: |
          pwd
          ls -R
          python3 app/main.py &
          curl http://0.0.0.0/isalive | tee getresult
          cat getresult
          jq '.status' getresult | grep 'OK'

